apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: $TEAM_NAME
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"