pipeline {
    agent any

    environment {
        DOCKER_HUB = "rajbhimani18"
        IMAGE_NAME = "multi-tenant-app"
        TEAM_NAME  = "team-b"
        IMAGE_TAG  = "team-b-${BUILD_NUMBER}"   // 🔥 IMPORTANT CHANGE
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_HUB/$IMAGE_NAME:$IMAGE_TAG ./app"
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push $DOCKER_HUB/$IMAGE_NAME:$IMAGE_TAG"
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                export TEAM_NAME=${TEAM_NAME}
                export DOCKER_IMAGE=${DOCKER_HUB}/${IMAGE_NAME}:${IMAGE_TAG}

                # Create namespace
                envsubst < k8s/namespace.yaml | kubectl apply -f -

                # Apply resource quota
                envsubst < k8s/resource-quota.yaml | kubectl apply -f -

                # Deploy app
                envsubst < k8s/deployment.yaml | kubectl apply -f -

                # Apply service
                envsubst < k8s/service.yaml | kubectl apply -f -
                """
            }
        }
    }
}