pipeline {
    agent any

    environment {
        DOCKER_HUB = "rajbhimani18"
        IMAGE_NAME = "multi-tenant-app"
        TEAM_NAME  = "team-a"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_HUB/$IMAGE_NAME:$BUILD_NUMBER ./app"
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh "docker login -u $USER -p $PASS"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push $DOCKER_HUB/$IMAGE_NAME:$BUILD_NUMBER"
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
        export TEAM_NAME=${TEAM_NAME}
        export DOCKER_IMAGE=${DOCKER_HUB}/${IMAGE_NAME}:${BUILD_NUMBER}

        # Create namespace
        envsubst < k8s/namespace.yaml | kubectl apply -f -

        # Apply resource quota
        envsubst < k8s/resource-quota.yaml | kubectl apply -f -

        # Deploy app
        envsubst < k8s/deployment.yaml | kubectl apply -f -

        # Apply service (FIXED)
        envsubst < k8s/service.yaml | kubectl apply -f -
        """
            }
        }
    }
}